services:
  db:
    image: postgres:15
    container_name: hospital_db
    restart: always
    environment:
      POSTGRES_USER: hospital
      POSTGRES_PASSWORD: hospital
      POSTGRES_DB: hospital
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hospital_network

  backend:
    image: marcusedemarchi/hospitaldc:backend
    container_name: hospital_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://hospital:hospital@db:5432/hospital
    depends_on:
      - db
    networks:
      - hospital_network

  frontend:
    image: marcusedemarchi/hospitaldc:frontend
    container_name: hospital_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - hospital_network

networks:
  hospital_network:
    driver: bridge

volumes:
  postgres_data: