# Estágio de construção (Build stage)
FROM node:18-slim AS build

WORKDIR /app

# Copia arquivos de dependência
COPY app/frontend/package*.json ./
RUN npm install

# Copia o restante do código
COPY app/frontend/ .

# Gera o build de produção
RUN npm run build

# Estágio de produção (Production stage)
FROM nginx:alpine

# Copia o build para o diretório do Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Expõe a porta 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
